baseURL = "https://jodo.hyogo.jp/"
hasCJKLanguage = true
languageCode = "ja-jp"
# Pagination
paginate =  5
paginatePath = "page"

theme = "hugo_theme_beg"
title = "兵庫杖道ナビ"
googleAnalytics = ""

[[menu.main]]
    name = "About"
    pre = "<i class='fa fa-heart'></i>"
    weight = -110
    identifier = "about"
    url = "/about/"
[[menu.main]]
    name = "Contact"
    pre = "<i class='fa fa-road'></i>"
    weight = -100
    identifier = "contact"
    url = "/contact/"