baseURL = "https://jodo.hyogo.jp/"
hasCJKLanguage = true
languageCode = "ja-jp"
enableGitInfo = true
# Pagination
paginate =  5
paginatePath = "page"
theme = "mainroad"
title = "兵庫杖道ナビ"
googleAnalytics = "UA-104503875-1"
[Params]
    description = "兵庫県の杖道情報をお送りします" # Description of your site. Used in meta description
    opengraph = true # Enable OpenGraph if true
    readmore = true # Show "Read more" button in list if true
    leftsidebar = false # Move sidebar to the left side if true
    authorbox = false # Show authorbox at bottom of pages if true
    post_navigation = true # Show post navigation at bottom of pages if true
    postSections = ["道場"] # the section pages to show on home page and the "Recent articles" widget
    #postSections = ["blog", "news"] # alternative that shows more than one section's pages
    #dateformat = "2006-01-02" # change the format of dates

[Params.widgets]
    search = true # Enable "Search" widget
    recent_articles = true # Enable "Recent articles" widget
    recent_articles_num = 5 # Set the number of articles in the "Recent articles" widget
    categories = true # Enable "Categories" widget
    tags = true # Enable "Tags" widget
    tags_counter = true # Enable counter for each tag in "Tags" widget (disabled by default)


